# Change this to your actual project name.
spring.application.name=dormdrop

# MongoDB configuration. Change details to match your MongoDB cluster.
spring.mongodb.uri=mongodb+srv://oogunbiyi24_db_user:2GSSbdLnMarcPERp@csc-305-lab-3.wy5oolk.mongodb.net
spring.mongodb.database=dormdrop

JWT_SECRET=
# Common prefix for all REST API endpoints.
api.prefix=/api/v1

# JWT is used for authentication. Needs a base64-encoded 256-bit secret
# key and session expiration time in milliseconds. (86400000 ms is 24 hours.)
app.jwt.secret=aEe42FEVj4raLI3KELNJddqdLHi9gZHK2Li8J8u9d9E=
app.jwt.expiration=86400000

project.admin.email=${ADMIN_EMAIL:admin@augustana.edu}
project.admin.password=${ADMIN_PASSWORD:admin}
project.admin.name=${ADMIN_NAME:Administrator}
